use M_UNIVER;

--1
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM inner join AUDITORIUM_TYPE 
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
--2
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM inner join AUDITORIUM_TYPE 
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%';
--3
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM, AUDITORIUM_TYPE 
	where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
select T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME from AUDITORIUM as T1, AUDITORIUM_TYPE as T2
	where T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE and T2.AUDITORIUM_TYPENAME like '%компьютер%';
--4
select STUDENT.NAME, FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME,  SUBJECT.SUBJECT_NAME,
	case
	when (PROGRESS.NOTE = 6) then 'шесть'
	when (PROGRESS.NOTE = 7) then 'семь'
	when (PROGRESS.NOTE = 8) then 'восемь'
	end[NOTE]
	from STUDENT inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP
		inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
		inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT
		inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
		inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY where PROGRESS.NOTE between 6 and 8  order by PROGRESS.NOTE desc

--5
select STUDENT.NAME, FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME,  SUBJECT.SUBJECT_NAME,
	case
	when (PROGRESS.NOTE = 6) then 'шесть'
	when (PROGRESS.NOTE = 7) then 'семь'
	when (PROGRESS.NOTE = 8) then 'восемь'
	end[NOTE]
	from STUDENT inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP
		inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
		inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT
		inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
		inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY where PROGRESS.NOTE between 6 and 8  
		order by 
				(case
					when (PROGRESS.NOTE = 6) then 3
					when (PROGRESS.NOTE = 7) then 1
					when (PROGRESS.NOTE = 8) then 2
				end)
--6
select PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME, '***')[TEACHER_NAME]
		from PULPIT left outer join TEACHER on PULPIT.PULPIT = TEACHER.PULPIT;
--7
select PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME, '***')[TEACHER_NAME]
		from TEACHER right outer join PULPIT on PULPIT.PULPIT = TEACHER.PULPIT;
--8
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM full outer join AUDITORIUM_TYPE 
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM_TYPE full outer join AUDITORIUM 
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;

select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM_TYPE full outer join AUDITORIUM 
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE where AUDITORIUM_TYPE.AUDITORIUM_TYPE is not null;

select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM_TYPE full outer join AUDITORIUM 
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE where AUDITORIUM.AUDITORIUM is not null;

--9
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM cross join AUDITORIUM_TYPE 
	where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
