use M_UNIVER;
--1
select PULPIT.PULPIT_NAME, FACULTY.FACULTY from PULPIT, FACULTY
	where FACULTY.FACULTY = PULPIT.FACULTY and FACULTY.FACULTY in (select PROFESSION.FACULTY from PROFESSION where (PROFESSION_NAME like '%технологи%'));
--2
select PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME from PULPIT inner join FACULTY
	on PULPIT.FACULTY = FACULTY.FACULTY where FACULTY.FACULTY in (select PROFESSION.FACULTY from PROFESSION where (PROFESSION_NAME like '%технологи%'));
--3
select distinct PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME from PULPIT inner join FACULTY
	on PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION
	on PROFESSION.FACULTY = FACULTY.FACULTY where PROFESSION.PROFESSION_NAME like '%технологи%';
--4
select AUDITORIUM_TYPE, AUDITORIUM_CAPACITY[MAX_CAPACITY], AUDITORIUM_NAME from AUDITORIUM a
		where AUDITORIUM_NAME = (select top(1) AUDITORIUM_NAME from AUDITORIUM aa
			where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc);
--5
select FACULTY_NAME from FACULTY
		where not exists (select * from PULPIT where FACULTY.FACULTY = PULPIT.FACULTY);
--6
select top(1)
	(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT = 'ОАиП')[OAIP],
	(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT = 'БД')[BD],
	(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECT = 'СУБД')[SUBD]
from PROGRESS;
--7
select AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME from AUDITORIUM 
	where AUDITORIUM_CAPACITY>=all(select AUDITORIUM_CAPACITY from AUDITORIUM where AUDITORIUM_NAME like '4%');
--8
select AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME from AUDITORIUM 
	where AUDITORIUM_CAPACITY>=any(select AUDITORIUM_CAPACITY from AUDITORIUM where AUDITORIUM_NAME like '4%');
